/**
 * Regression coverage for generated data-root README synchronization.
 *
 * These tests verify generated content and refresh behavior, not unrelated
 * repository document persistence.
 *
 * 生成されるdata-root READMEの同期に関する回帰テストです。
 *
 * これらのテストは生成内容と更新動作を検証し、無関係なリポジトリドキュメントの
 * 永続化は検証対象としません。
 *
 * @packageDocumentation
 */

import { readFile, writeFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { createTempRepo } from "./helpers.ts";

describe("data root README", () => {
  it("creates and refreshes the generated data-root README", async () => {
    const { repo } = await createTempRepo();

    const created = await repo.ensureDataRootReadme();
    const first = await readFile(created.path, "utf8");

    expect(created.changed).toBe(true);
    expect(first).toContain("<!-- task-mcp:data-root-readme -->");
    expect(first).toContain("cleanup_archive_candidates target=...");
    expect(first).toContain("request_logs/YYYY-MM-DD.jsonl");
    expect(first).toContain("per-file content summaries");
    expect(first).toContain("Mutating tools are serialized per data root");
    expect(first).toContain("Activity, Memory, And Reports");
    expect(first).toContain("latest display summary in `compact_summary`");
    expect(first).toContain("entries[].task_snapshot");
    expect(first).toContain("Current durable AI knowledge");
    expect(first).toContain("original record for later views");
    expect(first).toContain("Routine completion defers LLM/report generation");
    expect(first).toContain("Do not create new `task_summary` fields");
    expect(first).not.toContain("compact_pending_agent_updates");
    expect(first).toContain("Append-only source journal");
    expect(first).toContain("task_memory_promote_activity");
    expect(first).toContain("knowledge/notes/{id}.md");
    expect(first).toContain("knowledge/graph-index.json");
    expect(first).toContain("knowledge_promote_task_memory");
    expect(first).toContain("memory_policy=force");
    expect(first).toContain("cleanup_run_retention");
    expect(first).toContain("It never modifies task memory");
    expect(first).toContain("monitoring snapshots");
    expect(first).toContain("activity_append_entry");
    expect(first).not.toContain("upsert_activity_entry");
    expect(first).toContain("clear_override");
    expect(first).toContain("Legacy memory-summary history");
    expect(first).not.toContain("optimize_memory_summaries");
    expect(first).toContain("existing output is not replaced with deterministic text");
    expect(first).toContain("This README is generated by Personal Context MCP and overwritten on startup");
    [
      "README.md",
      "activities/",
      "agent_updates/",
      "backups/",
      "cleanup_archive/",
      "cleanup_summaries/",
      "config/",
      "contexts/",
      "inputs/",
      "memory_summaries/",
      "knowledge/",
      "outputs/",
      "projects/",
      "reports/",
      "task_memory/",
      "templates/",
    ].forEach((path) => {
      expect(first).toContain(path);
    });

    await writeFile(created.path, "# Old local README\n", "utf8");
    const refreshed = await repo.ensureDataRootReadme();
    const second = await readFile(created.path, "utf8");

    expect(refreshed.changed).toBe(true);
    expect(second).toBe(first);

    await expect(repo.ensureDataRootReadme()).resolves.toEqual({
      changed: false,
      path: created.path,
    });
  });
});
