/**
 * Coordinates external LLM providers and generated task artifacts.
 * Responsibility: This module owns memory promotion, scoped generation,
 * report generation, Tier summary generation, and persistence of generated task artifacts.
 * Non-responsibility: This module does not register MCP tools, initialize the protocol server, or own process lifecycle.
 *
 * 外部LLM Providerと生成されたタスク成果物を調整します。
 * 責務: このモジュールは、メモリ昇格、scoped generation、
 * report generation、Tier summary生成、および生成されたタスク成果物の永続化を担当します。
 * 非責務: このモジュールは、MCPツール登録、プロトコルサーバ初期化、プロセスライフサイクルを担当しません。
 *
 * @packageDocumentation
 */
import { createHash } from "node:crypto";
import { loadRelevantKnowledge } from "#app/knowledgeContext";
import type { SubmitAgentUpdateInput } from "#domain/agent-updates/workflow";
import {
  applyTaskMemoryPromotion,
  buildTaskMemoryPromotionPrompt,
  parseTaskMemoryPromotion,
  normalizeMemoryMindMap,
  type TaskMemoryPromotionInput,
  updateTaskMemoryMindMap,
} from "#domain/memory/actions";
import { generateDateReportWithExternalLlm } from "#domain/reports/generation";
import { promoteTaskMemoryToKnowledge } from "#domain/knowledge/promotion";
import { buildReportActivityCheckpoint, unreflectedActivities } from "#domain/reports/activitySync";
import { preserveReportEntryUrls } from "#domain/reports/urlPreservation";
import { replaceTaskCompactSummaries } from "#domain/tasks/actions";
import { isTaskDeleted } from "#domain/tasks/state";
import type { Repository } from "#infra/repository/repository";
import { recordKnowledgeUsage } from "#infra/audit/knowledgeUsage";
import type { ExternalLlmProvider, LlmGenerationRequest, LlmGenerationResult } from "#llm/types";
import type { GlobalMemoryDocument, ReportEntry, SourceRef } from "#shared/types";
import type { ToolRegistrationContext } from "#mcp/tools/context";
import { stripJsonFences } from "#mcp/llm/content";
import { createProviderExecution } from "#mcp/llm/providerExecution";
import { compactSummaryLines, memoryMindMapOutputSchema, memorySummaryOutputSchema } from "#mcp/llm/schemas";

interface GenerateAndApplyMemorySummaryResult {
  date: string;
  task_id?: string;
  llm_provider: ExternalLlmProvider | "unavailable" | "not_called";
  model?: string;
  stop_reason?: string;
  codex_thread_id?: string;
  codex_turn_id?: string;
  claude_session_id?: string;
  sampled_text?: string;
  skipped?: boolean;
  skip_reason?: "duplicate_input";
  parsed?: unknown;
  submitted?: unknown;
  applied?: unknown;
  fallback_reason?: string;
  fallback_reasons?: string[];
  fallback_reason_codes?: string[];
  fallback?: unknown;
  error?: string;
}

/**
 * Describes one task generated by a scoped LLM operation.
 *
 * scoped LLM操作で生成された1件のタスクを表します。
 */
export interface ScopedTaskGeneration {
  task_id: string;
  input_hash?: string;
  memory_update?: {
    summary: string[];
    facts: string[];
    decisions: string[];
    risks: string[];
    next: string[];
    mindmap?: unknown;
    sources: SourceRef[];
  };
  report_entry: { done: string[]; next: string[] };
  task_summary: string[];
}

/**
 * Describes a validated scoped generation result and its source revision.
 *
 * 検証済みscoped generation結果とその入力revisionを表します。
 */
export interface ScopedGenerationResult {
  date: string;
  source_revision: string;
  llm_provider: ExternalLlmProvider;
  model?: string;
  codex_thread_id?: string;
  codex_turn_id?: string;
  claude_session_id?: string;
  tasks: ScopedTaskGeneration[];
}

/**
 * Preserves user-facing URLs when an LLM omits them from generated updates.
 *
 * LLMが生成結果から落としたユーザー向けURLを保持します。
 */
export function preserveProposedUpdateUrls(
  tasks: ScopedTaskGeneration[],
  proposedUpdates: SubmitAgentUpdateInput[],
): void {
  for (const task of tasks) {
    const sources = proposedUpdates
      .filter((update) => update.task_id === task.task_id)
      .map((update) => ({ done: update.done, next: update.next }));
    preserveReportEntryUrls(task.report_entry, sources);
  }
}

/**
 * Exposes the LLM-backed operations assembled for one MCP server instance.
 *
 * 1つのMCPサーバインスタンス向けに組み立てられたLLM操作を公開します。
 */
export interface GenerationRuntime {
  generateStructured(request: LlmGenerationRequest, maxTokens?: number): Promise<LlmGenerationResult>;
  generateAndApplyMemorySummaryWithLlm(
    targetRepo: Repository,
    date: string,
    input: TaskMemoryPromotionInput,
    maxTokens?: number,
  ): Promise<GenerateAndApplyMemorySummaryResult>;
  generateTaskMemoryMindMapWithLlm(taskId: string, maxTokens: number): Promise<unknown>;
  promoteTaskMemoryToKnowledge(taskId: string, maxNotes: number, maxTokens: number): Promise<unknown>;
  generateScopedTaskUpdates(
    targetRepo: Repository,
    date: string,
    taskIds: string[],
    proposedUpdates?: SubmitAgentUpdateInput[],
    includeMemory?: boolean,
    proposedGlobalMemoryUpdates?: Pick<GlobalMemoryDocument, "summary" | "preferences" | "rules">,
  ): Promise<ScopedGenerationResult>;
  assertScopedGenerationCurrent(targetRepo: Repository, generated: ScopedGenerationResult): Promise<void>;
  applyScopedTaskUpdates(targetRepo: Repository, generated: ScopedGenerationResult): Promise<unknown>;
  generateDateReport(targetRepo: Repository, date: string, format: "text" | "markdown" | "html"): Promise<unknown>;
}

/**
 * Creates an isolated generation runtime with provider state scoped to one MCP server.
 *
 * Provider状態を1つのMCPサーバに限定した独立generation runtimeを作成します。
 */
export function createGenerationRuntime({ repo, config }: ToolRegistrationContext): GenerationRuntime {
  const { markProviderFailure, generateWithExternalProvider } = createProviderExecution(config);

  const selectedProvider = (): ExternalLlmProvider =>
    config.reportLlmProvider === "auto" ? "codex_app_server" : config.reportLlmProvider;

  /**
   * Generates one schema-constrained response with the provider selected for this MCP client.
   *
   * このMCPクライアント向けに選択されたProviderで、スキーマ制約付きレスポンスを1件生成します。
   */
  async function generateStructured(request: LlmGenerationRequest, _maxTokens = 3000): Promise<LlmGenerationResult> {
    return generateWithExternalProvider(selectedProvider(), request);
  }

  async function generateAndApplyMemorySummaryWithLlm(
    targetRepo: Repository,
    date: string,
    input: TaskMemoryPromotionInput,
    _maxTokens = 1200,
  ): Promise<GenerateAndApplyMemorySummaryResult> {
    const promptResult = await buildTaskMemoryPromotionPrompt(targetRepo, date, input);
    if (promptResult.skipped) {
      return {
        date,
        task_id: input.task_id,
        llm_provider: "not_called",
        skipped: true,
        skip_reason: promptResult.skip_reason,
        fallback: promptResult,
      };
    }
    if (!promptResult.prompt) throw new Error("Task memory promotion prompt was not generated.");
    const promotionPrompt = promptResult.prompt;
    const parseAndApply = async (text: string) => {
      const parsed = parseTaskMemoryPromotion(text, input.task_id);
      return {
        parsed,
        applied: await applyTaskMemoryPromotion(targetRepo, {
          task_id: input.task_id,
          input_hash: promptResult.input_hash,
          ...parsed,
        }),
      };
    };

    const provider = selectedProvider();
    try {
      const response = await generateWithExternalProvider(provider, {
        prompt: promotionPrompt,
        cwd: process.cwd(),
        outputSchema: memorySummaryOutputSchema(),
      });
      const appliedResult = await parseAndApply(response.text);
      return {
        date,
        task_id: input.task_id,
        llm_provider: provider,
        model: response.model,
        ...(provider === "codex_app_server"
          ? { codex_thread_id: response.threadId, codex_turn_id: response.turnId }
          : provider === "claude_cli"
            ? { claude_session_id: response.sessionId }
            : {}),
        sampled_text: response.text,
        ...appliedResult,
      };
    } catch (error) {
      const failureCode = markProviderFailure(provider, error);
      return {
        date,
        task_id: input.task_id,
        llm_provider: "unavailable",
        error: `${provider}: ${(error as Error).message}`,
        fallback_reason_codes: [failureCode],
        fallback: promptResult,
      };
    }
  }

  async function generateTaskMemoryMindMapWithLlm(taskId: string, _maxTokens: number) {
    const [tasks, memory] = await Promise.all([repo.loadTasks(), repo.loadTaskMemory(taskId)]);
    const task = tasks.tasks.find((item) => item.id === taskId);
    if (!task || isTaskDeleted(task)) throw new Error(`Task not found: ${taskId}`);
    const sharedMemory = {
      summary: memory.summary ?? [],
      facts: memory.facts ?? [],
      decisions: memory.decisions ?? [],
      risks: memory.risks ?? [],
      next: memory.next ?? [],
    };
    if (Object.values(sharedMemory).every((items) => items.length === 0)) {
      throw new Error(`Task memory has no content to map: ${taskId}`);
    }
    const prompt = [
      "Create a compact Japanese mind map from already-consolidated task memory.",
      "Return only JSON matching {mindmap:{root,paths}}.",
      "Use meaningful 4-6 level paths when supported by the memory.",
      "Organize each path by scope, concern, subject, and state.",
      "Every leaf must state a concrete current status, settled decision, active risk, or next action.",
      "Avoid vague standalone labels such as 状況, 対応, 確認, or 次.",
      "Keep each label under 32 Japanese characters and do not copy full memory sentences.",
      "The supplied payload intentionally excludes context, activities, inputs, sources, and file paths.",
      JSON.stringify({ task_id: taskId, title: task.title, memory: sharedMemory }),
    ].join("\n");
    const outputSchema = {
      type: "object",
      properties: { mindmap: memoryMindMapOutputSchema() },
      required: ["mindmap"],
      additionalProperties: false,
    };
    const provider = selectedProvider();
    const generated = await generateWithExternalProvider(provider, {
      prompt,
      cwd: process.cwd(),
      outputSchema,
    });
    const parsed = JSON.parse(stripJsonFences(generated.text)) as { mindmap?: unknown };
    const mindmap = normalizeMemoryMindMap(parsed.mindmap);
    if (!mindmap || mindmap.children.length === 0) throw new Error("Mind-map generation returned no usable paths.");
    const applied = await updateTaskMemoryMindMap(repo, taskId, mindmap);
    return {
      task_id: taskId,
      llm_provider: provider,
      model: generated.model,
      codex_thread_id: generated.threadId,
      codex_turn_id: generated.turnId,
      claude_session_id: generated.sessionId,
      shared_fields: Object.keys(sharedMemory),
      excluded_fields: ["context", "activities", "inputs", "sources", "file_paths"],
      mindmap,
      save: applied.save,
    };
  }

  async function promoteTaskMemoryToKnowledgeWithLlm(taskId: string, maxNotes: number, maxTokens: number) {
    return promoteTaskMemoryToKnowledge(repo, { task_id: taskId, max_notes: maxNotes }, (request) =>
      generateStructured(request, maxTokens),
    );
  }

  async function loadScopedGenerationSource(targetRepo: Repository, date: string, taskIds: string[]) {
    const uniqueTaskIds = [...new Set(taskIds.filter((taskId) => taskId.trim().length > 0))];
    const [tasksDoc, activity, inputs, globalMemory, reportSummary, report] = await Promise.all([
      targetRepo.loadTasks(),
      targetRepo.loadActivity(date),
      targetRepo.loadInputs(date),
      targetRepo.loadGlobalMemory(),
      targetRepo.loadReportSummary(date),
      targetRepo.loadReport(date),
    ]);
    const tasksById = new Map(tasksDoc.tasks.map((task) => [task.id, task]));
    const tasks = await Promise.all(
      uniqueTaskIds.map(async (taskId) => {
        const task = tasksById.get(taskId);
        if (!task || isTaskDeleted(task)) throw new Error(`Unknown task_id: ${taskId}`);
        const [context, memory] = await Promise.all([
          targetRepo.loadTaskContext(task),
          targetRepo.loadTaskMemory(taskId),
        ]);
        const knowledge = await loadRelevantKnowledge(
          targetRepo,
          [task.id, task.title, task.project, task.compact_summary, context.body, memory.summary, memory.facts],
          { limit: 10 },
        );
        const taskActivities = activity.entries.filter((entry) => entry.task_id === taskId);
        const existingReportEntry = report.entries.find((entry) => entry.task_id === taskId);
        return {
          task,
          context_frontmatter: context.data,
          context_body: context.body,
          existing_memory: memory,
          relevant_knowledge: knowledge,
          unreflected_activities: unreflectedActivities(taskActivities, existingReportEntry),
          existing_report_entry: existingReportEntry,
        };
      }),
    );
    const source = { date, tasks, inputs, global_memory: globalMemory, report_summary: reportSummary };
    return {
      source,
      revision: createHash("sha256").update(JSON.stringify(source)).digest("hex"),
    };
  }

  async function generateScopedTaskUpdates(
    targetRepo: Repository,
    date: string,
    taskIds: string[],
    proposedUpdates: SubmitAgentUpdateInput[] = [],
    includeMemory = false,
    proposedGlobalMemoryUpdates?: Pick<GlobalMemoryDocument, "summary" | "preferences" | "rules">,
  ): Promise<ScopedGenerationResult> {
    const uniqueTaskIds = [...new Set(taskIds.filter((taskId) => taskId.trim().length > 0))];
    if (uniqueTaskIds.length === 0) {
      throw new Error("At least one task_id is required for scoped generation.");
    }
    const loaded = await loadScopedGenerationSource(targetRepo, date, uniqueTaskIds);
    const taskSources = loaded.source.tasks.map((source) => ({
      ...source,
      proposed_updates: proposedUpdates.filter((update) => update.task_id === source.task.id),
    }));
    const prompt = [
      "Personal Context MCP scoped task finalization.",
      "Return only valid JSON matching the supplied schema.",
      `For every input task, produce one daily report entry and one Tier task-list summary${includeMemory ? ", plus one complete durable memory update" : ""}.`,
      "Use proposed_updates as new session facts that will be committed only after this response is validated.",
      "Keep activities as an append-only journal. Do not rewrite or compact source activities.",
      "Apply global_memory.rules as mandatory user-wide output constraints when relevant and compatible with the schema and source evidence.",
      "Apply global_memory.preferences to wording and presentation. Treat global_memory.summary as cross-task context, not dated work evidence.",
      "Use relevant_knowledge only as task-independent background for report_entry and task_summary. It cannot prove that dated work happened, and it must never be copied into memory_update.",
      "Treat proposed_global_memory_updates as explicit user-wide context for this generation. It is committed only after this response validates, so apply it without claiming it is already stored.",
      ...(includeMemory
        ? [
            "Memory contains only reusable facts, settled decisions, ongoing risks, and future-session context; never store dated work logs, monitoring snapshots, transient counts, report prose, or commands.",
            "Return memory_update as the complete durable state after removing duplicate, superseded, stale, and point-in-time information.",
            "For memory_update.mindmap, return {root, paths}. Each path should use 4-6 meaningful levels when supported by the source.",
            "Organize paths by scope, concern, subject, and state. Every leaf must state a durable fact, settled decision, ongoing risk, or future-session context.",
            "Avoid vague standalone labels such as 状況, 対応, 確認, or 次. Keep each Japanese label under 32 characters.",
          ]
        : ["Do not produce or modify task memory. Existing memory is read-only context for this report generation."]),
      "Report entries contain concise Japanese Done/Next only. Merge repeated monitoring snapshots into the latest meaningful state.",
      "Only unreflected_activities and proposed_updates are new. Reorganize them with existing_report_entry into the complete current report text.",
      "Preserve every user-facing HTTP/HTTPS URL from proposed_updates done/next verbatim in report_entry; never replace a URL with wording such as 'updated the report'.",
      "Task summary contains 1-2 concise bullets describing current stable state, blocker, deadline, or next direction.",
      "Do not expose commands, PID, raw internal keys, file paths, or implementation logs in report_entry or task_summary.",
      "Use short arrays and return every requested task_id exactly once.",
      "Source JSON:",
      JSON.stringify({
        ...loaded.source,
        proposed_global_memory_updates: proposedGlobalMemoryUpdates,
        tasks: taskSources,
      }),
    ].join("\n");
    const stringArraySchema = { type: "array", items: { type: "string" } };
    const sourceSchema = {
      type: "object",
      properties: {
        task_id: { type: ["string", "null"] },
        path: { type: ["string", "null"] },
        date: { type: ["string", "null"] },
        section: { type: ["string", "null"] },
      },
      required: ["task_id", "path", "date", "section"],
      additionalProperties: false,
    };
    const outputSchema = {
      type: "object",
      properties: {
        tasks: {
          type: "array",
          items: {
            type: "object",
            properties: {
              task_id: { type: "string" },
              ...(includeMemory
                ? {
                    memory_update: {
                      type: "object",
                      properties: {
                        summary: stringArraySchema,
                        facts: stringArraySchema,
                        decisions: stringArraySchema,
                        risks: stringArraySchema,
                        next: stringArraySchema,
                        mindmap: memoryMindMapOutputSchema(),
                        sources: { type: "array", items: sourceSchema },
                      },
                      required: ["summary", "facts", "decisions", "risks", "next", "mindmap", "sources"],
                      additionalProperties: false,
                    },
                  }
                : {}),
              report_entry: {
                type: "object",
                properties: { done: stringArraySchema, next: stringArraySchema },
                required: ["done", "next"],
                additionalProperties: false,
              },
              task_summary: stringArraySchema,
            },
            required: ["task_id", ...(includeMemory ? ["memory_update"] : []), "report_entry", "task_summary"],
            additionalProperties: false,
          },
        },
      },
      required: ["tasks"],
      additionalProperties: false,
    };
    const provider = selectedProvider();
    const response = await generateWithExternalProvider(provider, {
      prompt,
      cwd: process.cwd(),
      outputSchema,
    });
    const parsed = JSON.parse(stripJsonFences(response.text)) as { tasks?: ScopedTaskGeneration[] };
    if (!Array.isArray(parsed.tasks)) throw new Error("Scoped generation response is missing tasks.");
    const parsedTasks = parsed.tasks.map((task) => ({
      ...task,
      ...(includeMemory && task.memory_update
        ? {
            memory_update: {
              ...task.memory_update,
              mindmap: normalizeMemoryMindMap(task.memory_update.mindmap) ?? { root: task.task_id, children: [] },
            },
          }
        : {}),
      task_summary: compactSummaryLines(task.task_summary, task.task_id),
    }));
    const generatedIds = parsedTasks.map((task) => task.task_id);
    if (
      generatedIds.length !== uniqueTaskIds.length ||
      uniqueTaskIds.some((taskId) => generatedIds.filter((id) => id === taskId).length !== 1)
    ) {
      throw new Error("Scoped generation must return every requested task_id exactly once.");
    }
    if (includeMemory && parsedTasks.some((task) => !task.memory_update)) {
      throw new Error("Scoped memory promotion must return one memory_update for every requested task_id.");
    }
    preserveProposedUpdateUrls(parsedTasks, proposedUpdates);
    for (const task of parsedTasks) {
      const source = taskSources.find((item) => item.task.id === task.task_id);
      if (!source) continue;
      preserveReportEntryUrls(task.report_entry, [
        ...(source.existing_report_entry ? [source.existing_report_entry] : []),
        ...source.unreflected_activities,
      ]);
    }
    const tasks = parsedTasks.map((generatedTask) => {
      const source = taskSources.find((item) => item.task.id === generatedTask.task_id);
      if (!source) throw new Error(`Missing scoped source for task_id: ${generatedTask.task_id}`);
      return {
        ...generatedTask,
        input_hash: createHash("sha256").update(JSON.stringify({ date, source })).digest("hex"),
      };
    });
    await recordKnowledgeUsage(targetRepo, config, {
      workflow: "session_finish_task",
      stage: "injected_to_llm",
      date,
      provider,
      model: response.model,
      contexts: loaded.source.tasks.map((source) => ({
        task_id: source.task.id,
        knowledge: source.relevant_knowledge,
      })),
    }).catch((error: unknown) => console.error("Failed to write Knowledge usage log:", error));
    return {
      date,
      source_revision: loaded.revision,
      llm_provider: provider,
      model: response.model,
      codex_thread_id: response.threadId,
      codex_turn_id: response.turnId,
      claude_session_id: response.sessionId,
      tasks,
    };
  }

  async function assertScopedGenerationCurrent(
    targetRepo: Repository,
    generated: ScopedGenerationResult,
  ): Promise<void> {
    const current = await loadScopedGenerationSource(
      targetRepo,
      generated.date,
      generated.tasks.map((task) => task.task_id),
    );
    if (current.revision !== generated.source_revision) {
      throw new Error(
        "Scoped generation source changed while the LLM was running; retry to avoid overwriting newer data.",
      );
    }
  }

  async function generateDateReport(targetRepo: Repository, date: string, format: "text" | "markdown" | "html") {
    const provider = selectedProvider();
    return generateDateReportWithExternalLlm(targetRepo, config, date, format, provider, (request) =>
      generateWithExternalProvider(provider, request),
    );
  }

  async function applyScopedTaskUpdates(targetRepo: Repository, generated: ScopedGenerationResult) {
    const memoryResults = [];
    for (const item of generated.tasks) {
      if (!item.memory_update) continue;
      if (!item.input_hash) throw new Error(`Missing task memory checkpoint for task_id: ${item.task_id}`);
      memoryResults.push(
        await applyTaskMemoryPromotion(targetRepo, {
          task_id: item.task_id,
          input_hash: item.input_hash,
          ...item.memory_update,
          mindmap: normalizeMemoryMindMap(item.memory_update.mindmap),
        }),
      );
    }

    const compactSummaries = await replaceTaskCompactSummaries(
      targetRepo,
      generated.tasks.map((item) => ({
        task_id: item.task_id,
        compact_summary: item.task_summary,
      })),
    );
    const tasksById = new Map(compactSummaries.tasks.map((task) => [task.id, task]));
    const report = await targetRepo.loadReport(generated.date);
    const activity = await targetRepo.loadActivity(generated.date);
    const entries = [...report.entries];
    for (const item of generated.tasks) {
      const task = tasksById.get(item.task_id);
      if (!task) throw new Error(`Missing saved task for task_id: ${item.task_id}`);
      const index = entries.findIndex((entry) => entry.task_id === item.task_id);
      const existing = index >= 0 ? entries[index] : undefined;
      const existingMetadata = { ...(existing ?? { task_id: item.task_id }) };
      delete existingMetadata.task_summary;
      delete existingMetadata.done;
      delete existingMetadata.next;
      delete existingMetadata.source_activity_revision;
      delete existingMetadata.source_activity_ids;
      delete existingMetadata.activity_generated_at;
      const storedSummary = compactSummaryLines(task.compact_summary, item.task_id);
      const taskSnapshot = {
        title: task.title,
        ...(task.project !== undefined ? { project: task.project } : {}),
        ...(task.tier !== undefined ? { tier: task.tier } : {}),
        ...(task.status !== undefined ? { status: task.status } : {}),
        summary: storedSummary,
      };
      const entry: ReportEntry = {
        ...existingMetadata,
        task_id: item.task_id,
        ...(item.report_entry.done.length > 0 ? { done: item.report_entry.done } : {}),
        ...(item.report_entry.next.length > 0 ? { next: item.report_entry.next } : {}),
        ...buildReportActivityCheckpoint(activity.entries.filter((entry) => entry.task_id === item.task_id)),
        task_snapshot: taskSnapshot,
      };
      if (index >= 0) entries[index] = entry;
      else entries.push(entry);
    }
    const reportSave = await targetRepo.saveReport(
      generated.date,
      { date: generated.date, entries },
      "apply-scoped-task-generation",
    );
    return { memory_results: memoryResults, tasks_save: compactSummaries.save, report_save: reportSave };
  }

  return {
    generateStructured,
    generateAndApplyMemorySummaryWithLlm,
    generateTaskMemoryMindMapWithLlm,
    promoteTaskMemoryToKnowledge: promoteTaskMemoryToKnowledgeWithLlm,
    generateScopedTaskUpdates,
    assertScopedGenerationCurrent,
    applyScopedTaskUpdates,
    generateDateReport,
  };
}
