/**
 * Generated documentation for a configured Personal Context MCP data-root layout.
 *
 * This module owns only README content generation. It does not inspect the
 * filesystem, decide when to refresh the file, or perform persistence.
 *
 * 設定済みのPersonal Context MCP data-rootレイアウト向けドキュメントを生成します。
 *
 * このモジュールはREADME本文の生成のみを担当します。ファイルシステムの検査、
 * ファイルを更新するタイミングの判断、永続化処理は担当しません。
 *
 * @packageDocumentation
 */

import type { TaskMcpConfig } from "#shared/types";

const readmeMarker = "<!-- task-mcp:data-root-readme -->";

/**
 * Builds the complete generated data-root README for a configured layout.
 *
 * 設定されたレイアウト向けに、生成対象となるdata-root READMEの全文を構築します。
 */
export function buildDataRootReadme(layout: TaskMcpConfig["layout"]): string {
  return `${readmeMarker}
# Personal Context MCP Data Root

This README is generated by Personal Context MCP and overwritten on startup so it always reflects the current data-root layout.
Manual edits to this file are not preserved. Add durable notes to task/context/memory files instead.

This directory stores local Personal Context MCP state. It is intended to be readable by AI clients and safe to inspect manually.

## Directory Map

| Path | Purpose |
| --- | --- |
| \`README.md\` | This generated guide for the data-root structure. |
| \`${layout.tickets}\` | Version 1 canonical child-work ticket registry, separate from top-level Tasks. Created lazily; absent means no tickets. Mutations use repository transactions and dated backups, and append parent Activity progress snapshots. /tickets is the cross-task live board. No automatic utterance-to-ticket creation. |
| \`${layout.tasks}\` | Canonical task registry. Stores task id, title, project, status, tier, due date, context path, report flags, logical-delete flag, and the latest display summary in \`compact_summary\`. |
| \`${layout.contexts}/\` | Long-lived Markdown context for each task. Use this for task background, current assumptions, links, and working notes that should survive across sessions. |
| \`${layout.inputs}/YYYY-MM-DD.yaml\` | External inputs captured by date, such as manual notes, mail, calendar items, GitHub references, URLs, or incoming requests. |
| \`${layout.activities}/YYYY-MM-DD.yaml\` | Append-only source journal of dated work. It is the original record for later views. AI clients record factual work with \`activity_append_entry\` or \`session_finish_task\`; entries are not compacted, replaced, or deleted. |
| \`${layout.reports}/YYYY-MM-DD.yaml\` | Daily task history. Each \`entries[].task_snapshot\` preserves the task's state for that date; current task display data belongs in \`${layout.tasks}\` \`compact_summary\`. LLM generation uses the client-selected or environment-overridden Provider. If generation fails, existing output is not replaced with deterministic text. |
| \`${layout.outputs}/\` | Generated report files and artifacts. Canonical report outputs usually live under \`text/\`, \`markdown/\`, \`html/\`, or \`morning/\`. \`morning-progress/\` stores LLM assessments against the generated personal task table and is reset when that table is regenerated. |
| \`${layout.agentUpdates}/YYYY-MM-DD.yaml\` | Legacy internal session records retained for existing data compatibility. There is no public queue or approval workflow. |
| \`${layout.taskMemory}/{task_id}.yaml\` | Current durable AI knowledge for one task plus the latest promotion checkpoint: reusable facts, settled decisions, ongoing risks, and future-session context. Dated work logs, monitoring snapshots, and transient counts belong in activity/report data instead. |
| \`${layout.globalMemory}\` | Durable task-independent memory: cross-task context, user preferences, operating rules, and source references. Report, briefing, task-organization, and user-situation workflows read it automatically. It changes only through explicit Global Memory updates and is never derived automatically from Activity. |
| \`${layout.knowledge}/notes/{id}.md\` | Canonical task-independent Knowledge Graph notes. Each Markdown file stores readable content plus typed metadata, relations, aliases, tags, and evidence in YAML frontmatter. |
| \`${layout.knowledge}/graph-index.json\` | Derived Knowledge Graph index for bounded search and visualization. It is never the canonical source and can always be rebuilt from \`${layout.knowledge}/notes/\`. |
| \`${layout.people}/profiles/{id}.yaml\` | Canonical local-only person profiles. Confirmed, observed, and inferred facts remain explicitly distinguished and are never sent to an LLM automatically. Duplicate merges preserve source profiles as logical redirects with \`merged_into\` and record source IDs on the canonical profile with \`merged_from\`. |
| \`${layout.people}/relationships.yaml\` | Typed relationships between registered people. The user's own relationship to a person remains on that person's profile. |
| \`${layout.people}/interactions/YYYY-MM-DD.yaml\` | Append-only dated meetings, messages, commitments, outcomes, and follow-ups involving registered people. |
| \`${layout.reportSummaries}/YYYY-MM-DD.yaml\` | Internal daily report summary used to shape report output without relying only on raw report entries. |
| \`${layout.memorySummaries}/YYYY-MM-DD.yaml\` | Legacy memory-summary history. New versions do not write or maintain this directory. Existing files may be inspected or archived manually. |
| \`${layout.cleanupSummaries}/YYYY-MM-DD.yaml\` | Untruncated recursive manifests of archived cleanup candidates, including restore destinations and per-file content summaries when possible. |
| \`${layout.requestLogs}/YYYY-MM-DD.jsonl\` | MCP tool request audit log with compact argument/result metadata, correlation IDs when available, provider/fallback state, duration, and success/failure status. Knowledge usage events record workflow, stage, and Knowledge IDs so retrieval and LLM prompt injection can be audited. Prompts, note bodies, evidence text, and full generated text are not stored. |
| \`${layout.backups}/\` | Automatic backups created before overwriting existing YAML/Markdown files. |
| \`cleanup_archive/YYYY-MM-DD/{target}/\` | Archived cleanup candidates. These are restorable until deleted from the archive. |
| \`config/\` | Local runtime configuration. \`config/profile.yaml\` stores date settings, \`config/maintenance.yaml\` stores backup retention, and \`config/maintenance-state.yaml\` stores its last successful run. \`config/external_input.yaml\` optionally defines the external-input collector run before today's Web Summary generation. Explicit environment variables override stored values at startup. |
| \`projects/\` | Optional project-level notes or metadata that group multiple tasks under a project. Use when context belongs to a project rather than a single task. |
| \`templates/\` | Optional reusable templates for task contexts, reports, memory capture, or operating instructions. |

## Active Write Areas

| Path | Purpose |
| --- | --- |
| Task updates | \`${layout.tasks}\`, \`${layout.contexts}/\`, \`${layout.taskMemory}/\` |
| Daily session flow | \`${layout.activities}/\`, \`${layout.tasks}\` (latest \`compact_summary\`), \`${layout.reports}/\` (dated \`task_snapshot\`), \`${layout.reportSummaries}/\` |
| Memory and knowledge flow | \`${layout.taskMemory}/\`, \`${layout.globalMemory}\`, \`${layout.knowledge}/notes/\`, \`${layout.knowledge}/graph-index.json\` |
| People flow | \`${layout.people}/profiles/\`, \`${layout.people}/relationships.yaml\`, \`${layout.people}/interactions/\` |
| Report generation | \`${layout.outputs}/text/\`, \`${layout.outputs}/markdown/\`, \`${layout.outputs}/html/\`, \`${layout.outputs}/morning/\` |
| Cleanup flow | \`${layout.cleanupSummaries}/\`, \`cleanup_archive/\`, \`${layout.backups}/\` |
| Audit flow | \`${layout.requestLogs}/\` |

## Data Retention

| Path | Purpose |
| --- | --- |
| Durable state | \`${layout.tasks}\`, \`${layout.contexts}/\`, \`${layout.taskMemory}/\`, \`${layout.globalMemory}\`, \`${layout.knowledge}/notes/\`, \`projects/\`, \`templates/\`, \`config/\` |
| Dated operational state | \`${layout.inputs}/\`, \`${layout.activities}/\`, \`${layout.reports}/\`, \`${layout.reportSummaries}/\` |
| Legacy compatibility data | \`${layout.agentUpdates}/\`, \`${layout.memorySummaries}/\` |
| Regenerable artifacts | \`${layout.outputs}/\`, \`${layout.knowledge}/graph-index.json\` |
| Safety/audit data | \`${layout.backups}/\`, \`${layout.requestLogs}/\`, \`${layout.cleanupSummaries}/\`, \`cleanup_archive/\` |

## Cleanup Flow

Use cleanup as an archive-first flow:

1. \`cleanup_archive_candidates target=...\`
2. \`cleanup_restore_archive target=... dry_run=false\` if archived data was needed
3. \`cleanup_delete_archive target=... archive_date=YYYY-MM-DD dry_run=true\` to preview, then repeat with \`dry_run=false\` only after archive contents are no longer needed

\`cleanup_archive_candidates\` moves candidates to \`cleanup_archive\` and writes an untruncated recursive restorable manifest with per-file content summaries to \`${layout.cleanupSummaries}/\`. If the manifest cannot be saved, moved candidates are rolled back.
\`cleanup_delete_archive\` only removes files already under \`cleanup_archive\`; it does not delete unarchived source files.
\`cleanup_run_retention\` applies \`config/maintenance.yaml\`: it keeps all recent generations, then daily, weekly, and monthly generations, archives excess backups with a restorable manifest, and permanently deletes only archived backup data older than the configured grace period. It never deletes other cleanup targets.

## Activity, Memory, And Reports

\`config/profile.yaml\` controls the operational date. \`timezone\` uses an IANA name such as \`Asia/Tokyo\`; \`activity_rollover_hour: 0\` follows the calendar date, while a value such as \`4\` keeps times before 04:00 on the previous work date. Web settings update this file and the running configuration when no environment override is active. A settings change repartitions timestamped Activity entries with backups; legacy entries without a recoverable timestamp remain on their existing date and are reported to the Web client.

\`config/external_input.yaml\` controls the optional pre-Summary collector. When enabled, Personal Context MCP executes \`command\` directly without a shell, expands \`{date}\` and \`{data_root}\` in \`args\`, and provides \`TASK_MCP_DATA_ROOT\` plus an isolated \`TASK_MCP_COLLECTOR_STAGE_ROOT\` to the child process. \`locale\` defaults to \`en_US.UTF-8\` and is passed as both \`LANG\` and \`LC_ALL\` so Japanese external data is not interpreted as US-ASCII. The collector writes \`YYYY-MM-DD.yaml\` and briefing sections 1-3 as \`YYYY-MM-DD.md\` only into the stage root. Personal Context MCP validates both files and transactionally publishes them to \`${layout.inputs}/\` and \`${layout.outputs}/morning/\`; a failure leaves canonical data unchanged.

\`config/daily_task.yaml\` is the client-neutral source for the daily briefing name, prompt, schedule, model preference, workspace, and selected execution client. Personal Context MCP Web synchronizes Codex Automation directly. Cursor Automations, Claude Code \`/loop\`, Claude Desktop Scheduled Tasks, GitHub Copilot CLI, and Gemini CLI use generated setup instructions until those clients provide a documented local configuration API. Copilot and Gemini commands must be registered with an external scheduler. Only one execution client is selected; choosing a non-Codex client pauses the managed Codex automation to avoid duplicate runs.

\`${layout.activities}/\` is the append-only work source. \`task_memory_promote_activity\` explicitly consolidates reusable knowledge from existing task memory, task context, related inputs, and recent activity, then stores the complete latest durable state in \`${layout.taskMemory}/\`. It excludes dated work logs, monitoring snapshots, transient counts or percentages, report prose, commands, PIDs, and file paths. It keeps only the latest input hash and application time as a duplicate-prevention checkpoint; it does not create memory-summary history.

\`${layout.knowledge}/notes/\` stores reusable task-independent knowledge separately from user-wide rules in \`${layout.globalMemory}\`. Register a note only when it remains meaningful after removing the originating task name and date and can be reused across multiple tasks. Each note must be self-contained and embed its reusable claim, rationale, applicability, and limitations; local file paths and external references are not evidence. Keep dated work in Activity, task-specific state in Task Memory, and user-wide rules in Global Memory. AI clients should capture qualifying Knowledge proactively with \`knowledge_upsert_note\`, or include it in \`session_finish_task.knowledge_updates\` when closing a task session. Use \`knowledge_promote_task_memory\` explicitly after Task Memory contains a durable fact worth generalizing across tasks. It sends consolidated Task Memory, never raw Activity, to the configured LLM and returns no notes when nothing qualifies. Use \`knowledge_search_graph\` for bounded retrieval and \`knowledge_rebuild_graph\` to validate notes and regenerate the derived index.

\`report_generate_output\` reads durable memory as context, summarizes dated activity into \`entries[].task_snapshot\` history in \`${layout.reports}/\`, and writes a selected format under \`${layout.outputs}/\`. It never modifies task memory. \`report_render_output\` renders existing report data without an LLM call. Neither operation rewrites activity. The latest task-list display is \`${layout.tasks}\` \`compact_summary\`, not report history.

## Notes For AI Clients

- Read \`system_get_usage_guide\` before making broad changes.
- Before planning, making a decision, recommending an approach, designing a solution, or drafting content, call \`system_prepare_work\` with concise reusable domain concepts. Task-specific documents require task_id, scope=strict, include_context_body=true. Task IDs default to strict scope, without unrelated tasks or automatic Knowledge search; select knowledge_ids explicitly. Global Memory is opt-in via include_global_memory. Cross-task situation requires scope=global and include_global_situation=true, for cross-task planning only. Do not use other task facts as source evidence. Use \`knowledge_search_graph\` and \`knowledge_get_note\` for deliberate follow-up retrieval. Skip this for simple status reads or mechanical operations where Knowledge cannot affect the result.
- Use \`task_delete_item\` for duplicate or obsolete tasks. It writes \`deleted: true\` without removing related data; current lists, situation/search retrieval, Web monitoring, and report generation exclude the task. Use \`task_restore_item\` to restore it.
- Use \`activity_append_entry\` for intermediate checkpoints and call \`session_finish_task\` exactly once when one AI thread or task session actually ends. Exact retries with the same task and session id are idempotent. There is no public queue or human-approval workflow.
- Omit \`date\` for normal \`session_finish_task\` and \`activity_append_entry\` writes. Personal Context MCP selects the work date from offset-aware \`occurred_at\` (or request time), \`timezone\`, and \`activity_rollover_hour\`. An explicit historical \`date\` requires \`backfill=true\`.
- Treat \`${layout.activities}/\` as the append-only source journal, \`${layout.tasks}\` \`compact_summary\` as the latest task display, \`${layout.reports}/\` \`entries[].task_snapshot\` as daily history, and durable memory as task/global memory.
- \`TASK_MCP_LLM_PROVIDER=auto\` selects the matching Claude, Copilot, Cursor, or Gemini CLI for those clients, LM Studio's local API for LM Studio clients, Codex App Server for Codex/OpenAI/ChatGPT clients, and Codex App Server otherwise. An explicit \`codex_app_server\`, \`claude_cli\`, \`copilot_cli\`, \`cursor_cli\`, \`gemini_cli\`, or \`lm_studio\` value overrides detection; there is no cross-provider or deterministic report fallback.
- \`session_finish_task\` records Activity and current task state first. Routine completion defers LLM/report generation; terminal state transitions, \`processing_policy=immediate\`, \`memory_policy=force\`, or explicit output formats process immediately. Use \`report_generate_output\` to generate only tasks with unreflected Activity and render the complete date. Task memory is read-only unless \`memory_policy=force\` is explicit.
- HTTP/HTTPS URLs supplied in \`session_finish_task\` done/next are preserved verbatim in structured and rendered reports, even when the same URL appeared on the previous day.
- Codex App Server resolves its executable as \`TASK_MCP_CODEX_APP_SERVER_COMMAND\`, then \`CODEX_CLI_PATH\`, the macOS ChatGPT App-bundled CLI when present, then \`codex\` on \`PATH\`; its default args are \`app-server --listen stdio://\`. The model is fixed to \`gpt-6.1-sol\` by default; set \`TASK_MCP_CODEX_APP_SERVER_MODEL\` only to override it explicitly.
- Internal Codex App Server report and task-memory promotion requests start with \`ephemeral: true\`, so they are not materialized as persisted Codex tasks.
- Use \`${layout.contexts}/\` for task narrative context and \`${layout.taskMemory}/\` for compact durable facts.
- Use \`${layout.globalMemory}\` for always-applied user rules and preferences; use \`${layout.knowledge}/notes/\` for searchable concepts and typed relationships that apply beyond one task.
- Before creating a person, call \`people_find_duplicates\`. Exact email or phone reuse is rejected by default. Use \`people_merge_profiles\` only for confirmed duplicates; it keeps append-only interactions unchanged while making them retrievable from the canonical profile.
- Use \`projects/\` only when information applies to multiple tasks in the same project.
- Prefer \`cleanup_archive_candidates\` for general cleanup; restore from \`cleanup_archive\` if the archive was too aggressive. \`cleanup_run_retention\` applies configured backup retention, archives excess generations, and permanently removes only backup archives older than the grace period.
- Use \`activity_append_entry\` to add a journal entry. To shorten, replace, append to, or exclude report display text without changing activities, use the persistent \`report_update_entry\` override: \`replace\`, \`append\`, \`delete\` (exclude), or \`clear_override\` to return to normal generation.
- Use \`report_set_task_visibility\` to exclude or restore an entire task across generated reports. This preserves the task, Context, Task Memory, and Activity, and excluded tasks do not create unreflected-Activity warnings.
- Each Report Entry records the Activity revision and IDs incorporated into its generated text. Report generation sends only tasks with unreflected Activity to the LLM, while rendering the complete saved report. New Activity on a manually edited entry is reorganized with the existing text and the manual marker remains set.
- Use \`system_search_context\` for retrieval across tasks, contexts, inputs, activities, reports, and durable memory. Apply task/project/date/section filters for broad data roots.
- Do not create new \`task_summary\` fields. That legacy field is read-only compatibility data; write the latest display to \`${layout.tasks}\` \`compact_summary\` and daily history to report \`entries[].task_snapshot\`.
- Mutating tools are serialized per data root and saved with atomic replacement. Activity idempotency keys and task-memory checkpoints prevent duplicate updates.
`;
}
