/**
 * Provides usage guide capabilities for the application layer.
 * Responsibility: This module owns the usage guide behavior and contracts declared here.
 * Non-responsibility: This module does not own unrelated workflows or concerns assigned to other layers.
 *
 * application層のusage guide機能を提供します。
 * 責務: このモジュールは、ここで宣言するusage guideの振る舞いと契約を担当します。
 * 非責務: このモジュールは、無関係なワークフローや他の層に割り当てられた関心事を担当しません。
 *
 * @packageDocumentation
 */

/**
 * Performs the public `getUsageGuide` operation provided by this module.
 *
 * このモジュールが提供する公開操作`getUsageGuide`を実行します。
 */
export function getUsageGuide(): string {
  return [
    "# Personal Context MCP usage guide for AI clients",
    "",
    "## Small work tickets",
    "Delegation handoff: before sending substantial implementation work, the sender creates a ticket in todo and passes task_id, ticket_id, revision, scope and acceptance criteria to the receiving worker. The sender must not start it on the worker's behalf. Receipt alone leaves it todo. Only when actually starting work does the receiving worker read the latest revision and call ticket_start_item with its own assignee identity to move it to inProgress. Stale competing claims are rejected; reload and check ownership rather than overwriting another worker. Existing in-progress work remains inProgress. This is the canonical delegation policy; short checks, single commands and conversation are not ticketed.",
    "委任時は依頼元が実作業の送信前に未着手チケットを作成し、ID・revision・担当範囲・完了条件を渡します。依頼元は処理中へ移しません。実装側が依頼を受領して実際に着手する時に最新revisionを読み、自分を担当としてticket_start_itemで処理中へ移します。受領のみなら未着手を維持し、競合はrevisionで拒否します。短い確認・単一コマンド・会話はチケット化しません。",
    "Use ticket_create_item only for independently completable, substantial, delegated, or blocked work under an existing parent task. Do not ticket every utterance, short status check, single command, or casual conversation; those stay in Activity when useful. Never ask the user for ticket IDs. Existing Codex threads can handle multiple tickets sequentially; create a new thread only when explicitly authorized and useful for parallelism or isolation. Use ticket_list_items / ticket_get_item, ticket_start_item and ticket_update_item. waiting means a response, dependency, or specified date is expected before work resumes; blocked means a concrete obstruction prevents progress. Both require stop_reason. Use discarded with discard_reason only when duplicate, superseded, or no longer needed work will not be done. Discarded tickets remain in the audit history, are hidden from the normal board and open-ticket context, and can be restored by updating them to todo or inProgress with the latest revision. Never physically delete them during normal operation. Read revision before updates; reload conflicts instead of forcing them. Completion requires checked acceptance criteria and evidence. Supply ticket_id to activity_append_entry for detailed work. Ticket mutations append a parent Activity progress snapshot automatically; do not duplicate it. Context retains parent assumptions, Memory retains durable judgments, and report renderers aggregate non-discarded ticket progress under the parent rather than adding top-level tasks. The /tickets Web board shows all parent tasks and updates from the server via SSE.",
    "",
    "## Data flow",
    "",
    "`activity` is the append-only source journal. `tasks.yaml.compact_summary` is the latest task display, while `reports/YYYY-MM-DD.yaml` `entries[].task_snapshot` is dated history. `task_memory` stores reusable AI long-term knowledge. The normal flow is:",
    "",
    "1. Record dated work with `activity_append_entry`. For normal writes, omit `date`; Personal Context MCP derives the work date from `occurred_at`, timezone, and the configured rollover hour.",
    "2. Call `session_finish_task` exactly once when one AI thread or task session actually ends. Routine completion records Activity and current task state, then leaves report generation pending. It does not modify task memory by default. Supply `global_memory_updates` only when the session established an explicit rule, preference, or context that applies across tasks. Proactively include `knowledge_updates` when the session established a self-contained insight reusable across tasks; do not wait for a separate registration request.",
    "3. Use `report_generate_output` when a complete dated report is needed. It generates only tasks with unreflected Activity and then renders the complete report. Use `report_render_output` when report data already exists and only rendering is needed.",
    "",
    "`activities/YYYY-MM-DD.yaml` is never replaced, deleted, or compacted through the public API. It is the original work record. `reports/YYYY-MM-DD.yaml` preserves dated `entries[].task_snapshot` history, while the latest display stays in `tasks.yaml.compact_summary`. `outputs/text|markdown|html/YYYY-MM-DD.*` are generated renderings, not source data.",
    "",
    "## Start-of-work retrieval",
    "",
    "Before planning, making a decision, recommending an approach, designing a solution, or drafting content, call `system_prepare_work` with concise reusable domain concepts. For task-specific documents pass task_id, scope=strict, include_context_body=true. Task IDs default to strict isolation: only that task's situation, context and memory are returned. Knowledge requires explicit knowledge_ids in strict mode, without neighbor expansion. Global Memory requires include_global_memory=true. Cross-task planning must explicitly use scope=global and include_global_situation=true. Related tasks are not inferred from shared projects or words; retrieve them explicitly. Verify every task-specific assertion against task sources, not other tasks or reusable Knowledge.",
    "Use `knowledge_search_graph` for follow-up retrieval and `knowledge_get_note` for the complete content of useful matches. Apply the note's embedded evidence, applicability, and limitations.",
    "Use `knowledge_get_usage` to audit whether Knowledge was delivered to an AI client or injected into an internal LLM prompt. An `injected_to_llm` event proves prompt inclusion, not semantic adherence in the generated result.",
    "Do not use Knowledge as proof of today's work or task state. Read Activity for dated facts and Task Memory for task-specific durable context. Skip Knowledge retrieval for simple status reads or mechanical operations where domain knowledge cannot affect the result.",
    "",
    "## Normal session end",
    "",
    "Use `session_finish_task` once for one task's actual AI thread or work-session end. Do not call it for every checkpoint; use `activity_append_entry` during the session. Exact retries with the same `task_id` and `session_id` are idempotent.",
    "For normal session completion, omit `date`. Supply an offset-aware `occurred_at` when the work time differs from the request time. Use an explicit `date` only together with `backfill=true` for intentional historical import.",
    "The default `processing_policy=auto` defers LLM/report work for routine progress and processes immediately for terminal state transitions or explicit output formats. Use `processing_policy=immediate` only when the report snapshot must be refreshed now, or `deferred` to force Activity-first completion.",
    "Set `memory_policy=force` only when the session contains reusable facts, settled decisions, ongoing risks, or context needed in a future session. Keep `auto` or use `skip` for dated work logs, monitoring snapshots, transient counts, percentages, and report-only prose. `promote_memory` remains only as a deprecated compatibility input.",
    "",
    "Use `dry_run=true` only to preview this operation without writes. Omit `formats` for normal completion; requesting `formats=[text,markdown,html]` intentionally forces immediate report generation and rendering.",
    "",
    "## Tasks and context",
    "",
    "- `task_list_items`, `task_get_item`, `task_create_item`, and `task_update_item` manage current task state, including the latest `compact_summary` display value.",
    "- Status semantics are strict: `waiting` means work is expected to resume after an external response or event; `blocked` means the user explicitly stopped or suspended the task, or a concrete blocker prevents progress. Never record an explicit stop as `waiting`. Reports exclude `blocked` tasks while preserving them in task state and Activity history.",
    "- `task_delete_item` logically deletes a duplicate or obsolete task without removing its context, memory, activities, or report history. Deleted tasks are excluded from current retrieval and report generation. `task_restore_item` restores one.",
    "- `task_update_context` maintains a task's long-lived context separately from memory and daily reports.",
    "- `input_get_daily` and `input_upsert_item` manage dated external inputs.",
    "",
    "## Activity, reports, and outputs",
    "",
    "- `activity_get_daily` reads the append-only journal for a date; pass `task_id` to narrow it.",
    "- `activity_append_entry` records one dated fact for a task with `occurred_at` and `recorded_at`. Normal writes omit `date`; historical writes require `backfill=true`.",
    "- `report_get_daily` reads dated report history, including `entries[].task_snapshot`.",
    "- `report_set_task_visibility` includes or excludes one task from every generated report without deleting its Activity, Context, Task Memory, or task record. Excluded tasks do not create unreflected-Activity warnings. Use `visible=true` to include the task again.",
    "- `report_update_entry` makes a persistent per-date display override. Use `replace`, `append`, `delete`, or `clear_override` as needed.",
    "- `report_generate_output` reads durable memory as context, summarizes activities, refreshes dated `entries[].task_snapshot` history, and writes an output. It never modifies task memory.",
    "- Report outputs use one deterministic order across text, Markdown, and HTML. Tier task lists are grouped by `project` and ordered by Tier, project, status, `today_diff_order`, and task title. Daily differences retain their status sections and group tasks by project within each status.",
    "- `report_render_output` renders existing report data without generating new report entries.",
    "- `report_get_output` reads one generated output; `report_list_outputs` lists generated outputs.",
    "",
    "## Durable memory",
    "",
    "- `task_memory_get_state` and `task_memory_update_state` manage reusable facts, decisions, risks, and next context for one task.",
    "- `task_memory_promote_activity` selects durable information from a task's recent activity and promotes it into that task's memory.",
    "- `task_memory_generate_mindmap` sends only consolidated memory fields to the configured LLM and updates only `mindmap`; it requires explicit data-sharing consent.",
    "- `global_memory_get_state` and `global_memory_update_state` manage task-independent context, user-wide rules, and preferences. Global memory is always supplied to report, briefing, and task-organization generation, and is returned separately by `system_get_user_situation` so it cannot be dropped by task-context limits.",
    "- Global memory is updated explicitly. Activity is never promoted automatically. During normal work, use `session_finish_task.global_memory_updates` only for information that clearly applies beyond the current task.",
    "- `knowledge_search_graph` and `knowledge_get_note` retrieve self-contained task-independent concepts, systems, technologies, organizations, decisions, and documents with typed relations and embedded evidence.",
    "- `knowledge_get_usage` reports privacy-bounded Knowledge usage evidence by workflow and note ID without storing prompts, note bodies, evidence text, or generated output.",
    "- Put content in Knowledge only when it remains meaningful after removing the originating task name and date, is reusable across multiple tasks, and can explain why it holds, where it applies, and its limitations. Good example: `When a customer objects to price, identify whether ROI, budget timing, or value recognition is unresolved before responding.` Bad example: `Customer X rejected Task Y's quote today.`",
    "- Keep dated work, progress, transient observations, and one-task state in Activity or Task Memory. Keep user-wide preferences and operating rules in Global Memory. If content cannot be generalized beyond one task, do not create a Knowledge note.",
    "- `knowledge_upsert_note` maintains one self-contained Markdown Knowledge note. Include the reusable claim and its rationale in `evidence`; never use task ids, activity ids, file paths, URLs, or external references as a substitute for evidence. `knowledge_promote_task_memory` uses the configured LLM to generalize already-consolidated durable Task Memory, intentionally excludes Activity, returns no notes when nothing qualifies, and requires data-sharing consent. `knowledge_rebuild_graph` validates canonical notes and rebuilds the derived index.",
    "- Capture qualifying Knowledge proactively. During an active conversation use `knowledge_upsert_note` immediately when no task session will be finalized; otherwise include complete generalized notes in `session_finish_task.knowledge_updates`. Reuse an existing id for the same concept. The MCP validates and stores these notes without another LLM call or external data transfer.",
    "- Relevant bounded Knowledge neighborhoods may be supplied as background to reports and briefings. Knowledge is not copied implicitly into Task Memory and never proves that dated work happened; Activity remains the source for that claim.",
    "- `report_summary_get_daily` and `report_summary_update_daily` manage a report lead summary. It is report data, not task or global memory.",
    "",
    "## People and relationships",
    "",
    "- People is a separate local-only data domain for person profiles, the user's relationship to each person, person-to-person relationships, and append-only interaction history. It is not Knowledge, Task Memory, or Global Memory.",
    "- Use `people_list_profiles` and `people_get_profile` when a request requires information about a known person or relationship. Before creating a profile, call `people_find_duplicates` with the known name, aliases, organization, and contacts. Name and organization matches are candidates only; exact email or phone matches are strong identity conflicts. When durable person information appears in the conversation, capture it immediately; do not wait for the user to say register it. People data is never included in `system_prepare_work`, reports, briefings, or other LLM prompts automatically.",
    "- Prefer `people_capture_update` when one conversation provides profile changes, person-to-person relationships, or dated interactions together. It applies all supplied People changes in one rollback-capable transaction. Never infer missing fields, and provide `idempotency_key` for retryable interaction capture.",
    "- Use `people_upsert_profile` for user-provided or clearly observed profile information. Exact email or phone reuse is rejected by default; set `allow_duplicate=true` only after confirming the profiles represent different people. Every structured fact must remain marked as `confirmed`, `observed`, or `inferred`; never upgrade an inference without new evidence.",
    "- Use `people_record_interaction` for dated meetings, messages, commitments, outcomes, and follow-ups. Interactions are append-only and must not be copied into profile facts merely because they occurred.",
    "- Use `people_upsert_relationship` for typed relationships between two registered people. A stored relationship is retrieved from both endpoint profiles; symmetric relationships such as colleague are represented without direction in the Web graph. Use `people_merge_profiles` only for confirmed duplicates: it combines compatible profile information, rewires current relationships, preserves source profiles as `merged_into` redirects, and logically includes immutable source interactions under the canonical target. Conflicts abort the entire merge. Use `people_delete_profile` and `people_restore_profile` for ordinary reversible lifecycle changes; merged source profiles cannot be restored independently.",
    "- Before `session_finish_task`, check whether this session established durable person information that was not already captured. Put only those missing items in `people_updates`; do not duplicate information already written with `people_capture_update`.",
    "",
    "Store task-specific reusable facts, settled decisions, ongoing risks, and future-work context in task memory. Store cross-project user rules and preferences in global memory. Store only generalized, reusable, self-contained domain knowledge with embedded evidence in Knowledge. Store person profiles and relationships in People, and dated contact history in People interactions. Keep dated task facts in activities, daily snapshots in reports, and the latest task display in `tasks.yaml.compact_summary`. Do not write new legacy `task_summary` fields.",
    "",
    "## System and maintenance",
    "",
    "- `system_get_usage_guide`, `system_prepare_work`, `system_get_user_situation`, `system_search_context`, `system_list_data_dates`, and `system_validate_data` provide cross-cutting guidance, retrieval, cataloging, and validation.",
    "- `briefing_generate_daily` is the only AI-client entry point for today's briefing. External Calendar, Mail, and GitHub collection and sections 1-3 stay local; only curated active-task planning fields are sent to the configured LLM for sections 4-6. The tool saves the result and returns the Web URL. Never execute the configured collector script directly.",
    "- `cleanup_archive_candidates`, `cleanup_restore_archive`, and `cleanup_delete_archive` manage archived cleanup candidates. `cleanup_run_retention` applies the configured backup generations policy; it archives excess backups first and permanently deletes only expired backup archives after the grace period. Use `dry_run=true` to inspect its result without writes.",
    "",
    "## LLM provider selection",
    "",
    "The default `TASK_MCP_LLM_PROVIDER=auto` selects the matching Claude, Copilot, Cursor, or Gemini CLI for those clients, LM Studio's local API for LM Studio clients, Codex App Server for Codex/OpenAI/ChatGPT clients, and Codex App Server otherwise. `TASK_MCP_LLM_PROVIDER=codex_app_server|claude_cli|copilot_cli|cursor_cli|gemini_cli|lm_studio` always overrides client detection. Do not switch providers silently after a generation failure.",
    "Every Provider uses a fixed Provider-owned model with an environment override, isolated non-interactive execution, output limits, and request timeouts. Cursor and Gemini run from an empty temporary workspace so report generation does not expose the task repository as ambient CLI context. MCP and Web generation reuse the same selected external Provider.",
    "",
    "Public clients use only the APIs listed above. Internal processing is not a client workflow.",
  ].join("\\n");
}
